# yaml-language-server: $schema=https://raw.githubusercontent.com/LucasPickering/slumber/refs/tags/v4.2.1/schemas/config.json
# This config has been prepopulated with default values. For documentation, see:
# https://slumber.lucaspickering.me/api/configuration/index.html
editor: null
ignore_certificate_hosts: []
large_body_size: 1000000
follow_redirects: true
commands:
  shell:
  - /bin/sh
  - -c
  default_query: {}
pager: {}
preview_templates: true
input_bindings:
  quit:
  - q
  force_quit:
  - ctrl c
  scroll_left:
  - shift left
  scroll_right:
  - shift right
  open_actions:
  - x
  open_help:
  - '?'
  fullscreen:
  - f
  reload_collection:
  - f5
  history:
  - h
  search:
  - /
  export:
  - ':'
  previous_pane:
  - shift tab
  next_pane:
  - tab
  up:
  - up
  down:
  - down
  left:
  - left
  right:
  - right
  page_up:
  - pageup
  page_down:
  - pagedown
  home:
  - home
  end:
  - end
  submit:
  - enter
  toggle:
  - space
  cancel:
  - escape
  delete:
  - delete
  edit:
  - e
  reset:
  - z
  view:
  - v
  select_collection:
  - f3
  select_profile_list:
  - p
  select_recipe_list:
  - l
  select_recipe:
  - c
  select_response:
  - r
theme:
  primary_color: Blue
  primary_text_color: White
  secondary_color: Yellow
  success_color: Green
  error_color: Red
persist: true
